### ISSUE TITLE
URL request error.

### ISSUE THREAD

**Issue by wxguy** [bastibe/meteogram#6]
Tried to execute your script today. It seems that yr.no site removed the version 1.8 of the api. The latest one is version 1.9. I have change the api version to latest one and tested again. But it still resulted in following error:-

```
$ python meteogram_auto.py 
Traceback (most recent call last):
  File "meteogram_auto.py", line 288, in <module>
    fig = plot_meteogram('Oldenburg, Germany')
  File "meteogram_auto.py", line 246, in plot_meteogram
    latLng = retrieve_position_openmapquest(address)
  File "meteogram_auto.py", line 78, in retrieve_position_openmapquest
    request = urlopen(complete_url)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Again I have changed the `request` line with `request = urlopen(complete_url, headers={'User-Agent': 'Mozilla/5.0'})` but it produces the same error.

**Comment by bastibe** [comment]
You will have to change the actual source code in `retrieve_weather_yrno` . At least the URL will have to be changed, and possibly the code in `XML_time_node_to_dict` (if there were significant changes to the XML format between 1.8 and 1.9).

If you get this working again, I would be very happy to merge the updated program!

**Comment by wxguy** [comment]
I have done that already. It seems like the same error occur in `retrieve_position_openmapquest` function as well. I am not comfortable with python 3. Will check it out later.

**Comment by bastibe** [comment]
If you did change the URL and it still doesn't work, the API changed the XML structure. I'm afraid you'll have to change the Python code, then. I currently don't have the time to do it for you.
